baseURL = "/"
languageCode = "en-us"
title = "Sung Sam Gong, PhD"
theme = "ezhil"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-145279805-1"
disqusShortname = "localhost"

ignoreFiles=["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
    #Blog subtitle which appears below blog title. Supports markdown.
	subtitle = "[Senior Research Associate in Bioinformatics](https://www.obgyn.cam.ac.uk/staff/research-staff/sung-gong/)<br>[Department of Obstetrics & Gynaecology](https://www.obgyn.cam.ac.uk/)<br>University of Cambridge"
	# Number of posts to show in recent posts list.
	recentPostsCount = 5
    # Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	excludedTypes = ["page"]
    # Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	disableDisqusTypes = ["page"]
    # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	featherIconsCDN = true
    footer = "&copy; [Sung Gong](http://sung.bio.cc) 2019"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv"
weight = 2 

[[menu.main]]
name = "About"
url = "/about"
weight = 3 

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 2

#[[menu.main]]
#name = "Tags"
#url = "/tags"
#weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/sung"

[[params.social]]
name = "GitLab"
icon = "gitlab"
url = "https://gitlab.com/sunggong"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/sunggong"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/sunggong/"


#[[params.social]]
#name = "RSS"
#icon = "rss"
#url = "/index.xml"

[taxonomies]
   tag = "tags"
